### ISSUE TITLE
前端方案调研

### ISSUE THREAD

**Issue by RunanWang** [RyanMrW/somewhere#2]
涉及到前端问题的部分主要有三个：用户端的购买界面、商户的界面，以及平台的管理界面，为避免麻烦，三个界面采用一个系统来写。在已经确定用go来写后端的前提下，前端应采用RESTFUL接口形式来实现。

考虑完全用web来实现全部的功能。

**Comment by RunanWang** [comment]
目前的想法是不把前端作为主要的部分来写，主要的精力放在后端和算法上。即前端想办法去套用一些模板。

在调研中发现可以采用vue的方法，正在进行调研进行一些更改的难度。

**Comment by RunanWang** [comment]
gin+vue参考：https://github.com/Bingjian-Zhu/gin-vue

**Comment by RunanWang** [comment]
gin+vue参考：https://github.com/piexlmax/gin-vue-admin

**Comment by piexlmax** [comment]
闲暇时间做的小项目 很荣幸被您作为参考

**Comment by RunanWang** [comment]
经过讨论确认采用vue，在12月之内学完，决定下一步是自己做还是套模板。
